### ISSUE TITLE
Write a short description of the extension 

### ISSUE THREAD

**Issue by emma-hubka** [BracciaCJ/2022-CornHacks#6]

**Comment by BracciaCJ** [comment]
[NAME] allows users to discover wheter or not a website will be accessible to them before even opening the website. [Name]  Google Chrome Extension scores and displays the accessibility score of websites directly in a google search for users with disabilities. 
Users can select their disability when first signing up and the results will be tailor to them, otherwise their is also a default score for general accesibility.

**Comment by BracciaCJ** [comment]
also created google extension 132 character description as below

Ha11y can discover and rate websites accessibility levels based on a set disability or simply overall disability.

**Comment by emma-hubka** [comment]
[NAME] allows users to discover whether or not a website will be accessible to them before even opening the website. [Name] Google Chrome Extension scores and displays the accessibility score of websites directly in a google search for users with disabilities. Users can select their disability when first signing up and the results will be tailored to them, otherwise, there is also a default score for general accessibility.
